source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'CJUIKit_Example' do #, :exclusive => true do
  pod "CJUIKit", :path => "../"
end

#target 'CJUIKit_Tests' do # , :exclusive => true do
#  pod "CJUIKit", :path => "../"
#
#  pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
#end
